files:
  ignore:
    - 'src/assets/scss/_vars.scss'
rules:
  brace-style:
    - 2
    -
      allow-single-line: true

  class-name-format: 0
  declarations-before-nesting: 2
  empty-line-between-blocks: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  indentation: 0
  leading-zero: 0
  nesting-depth:
    - 2
    -
      max-depth: 4

  no-color-keywords: 2
  no-color-literals: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  empty-args: 0
  no-extends: 2
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    -
      'extra-properties':
        - 'scrollbar-width'
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-vendor-prefixes: 0
  no-qualifying-elements: 0
  no-warn: 2
  one-declaration-per-line: 2
  property-sort-order: 0
  pseudo-element: 2
  quotes:
    - 2
    -
      style: single
  single-line-per-selector: 2
  space-after-colon: 2
  space-before-brace: 2
  trailing-semicolon: 2
  zero-unit: 0
