version: '3'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
