FROM node:latest as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build /app/dist /app
COPY /nginx/nginx.conf /etc/nginx/nginx.conf
