version: '3'

services:
  web-prod:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
    volumes:
       - ./:/app
       - /app/node_modules
