version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: web
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
